r"""Fixed-rank LOBPCG-style solver for Hermitian positive-definite TT systems.

``lobpcg_solve`` minimizes

.. math::

    E(x) = \tfrac12 \langle x, A x\rangle - \Re\langle f, x\rangle

on the manifold of tensors having the rank profile of ``x0``.  It uses a
one-site alternating sweep.  At site ``k`` the local correction equation is
solved by augmented PCG in the affine space generated by

``[current core, preconditioned residual, transported previous direction]``.

There is one remembered direction per TT core.  A direction saved on the
previous sweep represents the ambient tensor ``V_old p``; before reuse it is
projected into the new one-core chart as ``V_new.H V_old p``.  The overlap
factorizes into one left and one right frame contraction, so neither the full
tensor nor a dense tangent chart is formed.

This is deliberately a separate algorithm from :func:`tt.amen_solve`.  AMEn
enriches TT bases and adapts ranks.  This solver never enriches, truncates, or
uses an SVD: every bond dimension stays equal to the corresponding dimension
of ``x0``.

Notes
-----
The name follows the LOBPCG three-term idea, but the problem is a linear SPD
system rather than an eigenproblem.  The stopping quantity is the norm of the
horizontal projected energy gradient, divided by ``||f||``.  It certifies a
stationary point of the *fixed-rank* problem; it is not the same as the full
linear residual when the selected ranks cannot represent the exact solution.
Set ``check_true_res=True`` to report the latter as well.

Backend agnostic: every array operation goes through :mod:`tt.backend`, so the
solver runs unchanged on numpy and on torch (CPU or GPU) cores; ``A`` and ``f``
are brought to the backend of ``x0``, which owns the answer.  The only numpy in
here is the host-side bookkeeping (ranks, convergence tests, printing) and the
compiled float64 local kernel, which is one branch of a dispatch whose other
branch is the pure implementation.
"""

from __future__ import annotations

import math
import time
import warnings
from dataclasses import dataclass, field

import numpy as np

from .. import backend as bk
from ..core import _ops
from ..core.vector import vector
from . import _fast
from .amen import (
    RESID_DAMP,
    _blas_layout,
    _canon_prec,
    _jacobi,
    _jacobi_c_inverse,
    _local_operator,
    _local_rhs,
    _push_left,
    _push_right,
    _qr_left,
    _rq_right,
    _vdot,
)
from .amen_mv import (
    _matrix_cores,
    _phi_next,
    _phi_yy_next,
    _project,
    _vector_cores,
)

__all__ = ["LOBPCGSolveHistory", "lobpcg_solve"]

#: Smallest positive float64.  It only ever guards a division by a *host* scalar
#: (``||rhs||`` of a local block), so it is a plain Python constant and not a
#: per-backend quantity: it is below the smallest normal of every dtype the
#: package supports, which is all a guard needs to be.
_TINY = float(np.finfo(np.float64).tiny)


@dataclass
class LOBPCGSolveHistory:
    """Diagnostics produced by :func:`lobpcg_solve`.

    ``projected_gradient`` is
    ``||P_T(A x - f)|| / ||f||`` in horizontal fixed-rank coordinates.
    ``true_res`` is ``||A x-f||/||f||`` and remains ``nan`` unless requested.
    ``sweeps`` contains cumulative timings and local-work counters for every
    completed sweep.
    """

    tol: float
    sweeps: list = field(default_factory=list)
    converged: bool = False
    projected_gradient: float = float("nan")
    initial_projected_gradient: float = float("nan")
    true_res: float = float("nan")
    ranks: list = field(default_factory=list)
    nswp_done: int = 0
    time: float = 0.0
    local_matvecs: int = 0
    recycled_directions: int = 0
    message: str = ""

    def __repr__(self):
        max_rank = max(self.ranks) if self.ranks else 0
        return (
            f"LOBPCGSolveHistory(sweeps={self.nswp_done}, "
            f"converged={self.converged}, "
            f"projected_gradient={self.projected_gradient:.2e}, "
            f"true_res={self.true_res:.2e}, max_rank={max_rank}, "
            f"time={self.time:.2f}s)"
        )


def _interfaces(depth, boundary):
    result = [None] * (depth + 1)
    result[0] = bk.copy(boundary)
    result[depth] = bk.copy(boundary)
    return result


def _copy_cores(cores):
    return [bk.copy(core) for core in cores]


def _numel(a):
    """Number of entries of a backend array (torch spells ``.size`` a method)."""
    total = 1
    for extent in a.shape:
        total *= int(extent)
    return total


def _ones(shape, like):
    """``ones`` on the backend and dtype of ``like`` (no ``bk.ones`` exists)."""
    return bk.zeros(shape, dtype=bk.dtype_of(like), like=like) + 1.0


def _conj_t(a):
    """``a^H`` of a matrix.  ``.T`` is numpy-only spelling for a permutation."""
    return bk.transpose(a.conj(), (1, 0))


def _check_fixed_profile(cores):
    ranks = [int(value) for value in _ops.ranks(cores)]
    modes = [int(core.shape[1]) for core in cores]
    for site, mode in enumerate(modes[:-1]):
        if ranks[site + 1] > ranks[site] * mode:
            raise ValueError(
                f"x0 rank profile {ranks} is not left-feasible at bond "
                f"{site + 1}: {ranks[site + 1]} > {ranks[site]}*{mode}"
            )
    for site in range(1, len(modes)):
        if ranks[site] > modes[site] * ranks[site + 1]:
            raise ValueError(
                f"x0 rank profile {ranks} is not right-feasible at bond "
                f"{site}: {ranks[site]} > {modes[site]}*{ranks[site + 1]}"
            )
    return ranks


def _right_canonicalize(acores, fcores, xcores, one, one2):
    """Put the center at site zero and build the right environments."""
    depth = len(xcores)
    phia_right = _interfaces(depth, one)
    phif_right = _interfaces(depth, one2)
    right_frame = [None] * depth
    for site in range(depth - 1, 0, -1):
        factor, core = _rq_right(xcores[site])
        xcores[site] = core
        right_frame[site] = bk.copy(core)
        xcores[site - 1] = _push_right(xcores[site - 1], factor)
        phia_right[site] = _phi_next(
            _project(phia_right[site + 1], acores[site], core, "rl"),
            core,
            "rl",
        )
        phif_right[site] = _phi_yy_next(
            phif_right[site + 1], core, fcores[site], "rl"
        )
    # It is not part of a right frame used by a local chart, but keeping the
    # slot populated makes snapshots self-describing and easier to inspect.
    right_frame[0] = bk.copy(xcores[0])
    return phia_right, phif_right, right_frame


def _right_frame_overlaps(old, new):
    """All ``R_old.H R_new`` contractions needed to transport core vectors."""
    depth = len(new)
    result = [None] * (depth + 1)
    result[depth] = _ones((1, 1), new[-1])
    overlap = result[depth]
    for site in range(depth - 1, 0, -1):
        old_core = old[site]
        new_core = new[site]
        old_left, mode, old_right = old_core.shape
        contracted = (
            old_core.reshape(old_left * mode, old_right) @ overlap
        ).reshape(old_left, mode * new_core.shape[2])
        overlap = contracted @ _conj_t(
            new_core.reshape(new_core.shape[0], mode * new_core.shape[2])
        )
        result[site] = overlap
    return result


def _transport_direction(direction, left_overlap, right_overlap):
    """``V_new.H V_old direction`` in factored one-core coordinates."""
    old_left, mode, old_right = direction.shape
    first = left_overlap @ direction.reshape(old_left, mode * old_right)
    return (
        first.reshape(left_overlap.shape[0] * mode, old_right) @ right_overlap
    ).reshape(left_overlap.shape[0], mode, right_overlap.shape[1])


def _valid_direction(direction):
    if direction is None:
        return None
    norm = float(bk.norm(direction))
    threshold = (1000.0 * bk.eps_of(bk.dtype_of(direction))
                 * math.sqrt(_numel(direction)))
    if not math.isfinite(norm) or norm <= threshold:
        return None
    return direction / norm


def _generic_augmented_pcg(apply, precondition, rhs, coarse, tol, steps):
    """Backend-independent formula used when the fused float64 path is absent."""
    shape = rhs.shape
    right = rhs.reshape(-1)
    right_norm = float(bk.norm(right))
    eps_mach = bk.eps_of(bk.dtype_of(right))
    correction = bk.zeros(right.shape, dtype=bk.dtype_of(right), like=right)
    residual = bk.copy(right)
    matvecs = 0
    coarse_ok = False
    hp = None
    denominator = 0.0

    def matvec(value):
        return apply(value.reshape(shape)).reshape(-1)

    if coarse is not None:
        coarse = coarse.reshape(-1)
        hp = matvec(coarse)
        matvecs += 1
        denominator = float(_vdot(coarse, hp).real)
        scale = math.sqrt(float(_vdot(coarse, coarse).real)
                          * float(_vdot(hp, hp).real))
        if denominator > 100.0 * eps_mach * scale:
            alpha = _vdot(coarse, residual) / denominator
            correction = correction + alpha * coarse
            residual = residual - alpha * hp
            coarse_ok = True

    def projected_precondition(value):
        z = bk.copy(precondition(value.reshape(shape)).reshape(-1))
        if coarse_ok:
            z = z - coarse * (_vdot(hp, z) / denominator)
        return z

    zvec = projected_precondition(residual)
    rho = float(_vdot(residual, zvec).real)
    search = bk.copy(zvec)
    last_search = None
    used = 0
    breakdown = False
    fresh_budget = max(int(steps) - int(coarse is not None), 0)
    for _ in range(fresh_budget):
        if float(bk.norm(residual)) <= tol * right_norm:
            break
        image = matvec(search)
        matvecs += 1
        curvature = float(_vdot(search, image).real)
        scale = math.sqrt(float(_vdot(search, search).real)
                          * float(_vdot(image, image).real))
        if curvature <= 100.0 * eps_mach * scale or rho <= 0.0:
            breakdown = True
            break
        last_search = bk.copy(search)
        used += 1
        alpha = rho / curvature
        correction = correction + alpha * search
        residual = residual - alpha * image
        if float(bk.norm(residual)) <= tol * right_norm:
            break
        zvec = projected_precondition(residual)
        rho_new = float(_vdot(residual, zvec).real)
        if rho_new <= 0.0:
            breakdown = True
            break
        search = zvec + (rho_new / rho) * search
        rho = rho_new

    memory = last_search if last_search is not None else (
        coarse if coarse_ok else None
    )
    relative = float(bk.norm(residual)) / max(right_norm, _TINY)
    return correction.reshape(shape), _valid_direction(
        None if memory is None else memory.reshape(shape)
    ), {
        "matvecs": matvecs,
        "fresh_steps": used,
        "coarse_used": int(coarse_ok),
        "relative_residual": relative,
        "breakdown": breakdown,
    }


def _augmented_pcg(phi_left, acore, phi_right, rhs, coarse, tol, steps,
                   prec_kind):
    """Solve one local correction equation and return its next memory vector.

    The fused kernel below is compiled for contiguous real float64 *numpy*
    buffers and nothing else, so the dispatch is the one used throughout the
    package (``amen_mv._project``): the compiled path when the block is such an
    array, the backend-agnostic :func:`_generic_augmented_pcg` otherwise --
    complex blocks, float32, and every torch/GPU block.  The two paths compute
    the same recurrence, so the choice is a cost decision only.
    """
    apply, shape = _local_operator(phi_left, acore, phi_right)
    coarse = _valid_direction(coarse)
    precondition = (
        bk.copy
        if prec_kind == "n"
        else _jacobi(prec_kind, phi_left, acore, phi_right)
    )
    fast = (
        _fast.HAVE_NUMBA
        and type(rhs) is np.ndarray
        and rhs.dtype == np.float64
        and prec_kind in ("n", "c")
    )
    inverse = None
    if fast and prec_kind == "c":
        inverse = _jacobi_c_inverse(phi_left, acore, phi_right)
        fast = inverse is not None

    if not fast:
        return _generic_augmented_pcg(
            apply, precondition, rhs, coarse, tol, steps
        )

    a, i, p = phi_left.shape
    b, j, c = phi_right.shape
    _, n, m, _ = acore.shape
    phi1, amat, phi2 = _blas_layout(phi_left, acore, phi_right)
    coarse_flat = (
        np.zeros(rhs.size, dtype=rhs.dtype)
        if coarse is None
        else np.ascontiguousarray(coarse.reshape(-1))
    )
    fresh_budget = max(int(steps) - int(coarse is not None), 0)
    result = _fast.recycled_pcg_local(
        phi1,
        amat,
        phi2,
        inverse if inverse is not None else np.zeros((1, 1, 1, 1)),
        inverse is not None,
        np.ascontiguousarray(rhs.reshape(-1)),
        coarse_flat,
        coarse is not None,
        float(tol),
        fresh_budget,
        i,
        m,
        j,
        p,
        n,
        c,
        b,
        a,
    )
    correction, residual, last, matvecs, used, breakdown, coarse_ok = result
    memory = last if used else (coarse_flat if coarse_ok else None)
    right_norm = float(bk.norm(rhs))
    return correction.reshape(shape), _valid_direction(
        None if memory is None else memory.reshape(shape)
    ), {
        "matvecs": int(matvecs),
        "fresh_steps": int(used),
        "coarse_used": int(coarse_ok),
        "relative_residual": float(bk.norm(residual)) / max(
            right_norm, _TINY
        ),
        "breakdown": bool(breakdown),
    }


def _projected_gradient_norm(acores, fcores, cores, fnorm, one, one2):
    """Exact horizontal tangent-gradient norm without a dense tangent basis."""
    work = _copy_cores(cores)
    phia_right, phif_right, _ = _right_canonicalize(
        acores, fcores, work, one, one2
    )
    depth = len(work)
    phia_left = _interfaces(depth, one)
    phif_left = _interfaces(depth, one2)
    norm_squared = 0.0
    for site in range(depth):
        rhs = _local_rhs(phif_left[site], fcores[site], phif_right[site + 1])
        residual = (
            _local_operator(
                phia_left[site], acores[site], phia_right[site + 1]
            )[0](work[site])
            - rhs
        )
        residual_norm_squared = float(_vdot(residual, residual).real)
        if site == depth - 1:
            norm_squared += residual_norm_squared
            continue
        core, factor = _qr_left(work[site])
        core_matrix = core.reshape((-1, core.shape[2]))
        residual_matrix = residual.reshape((-1, residual.shape[2]))
        gauge = _conj_t(core_matrix) @ residual_matrix
        horizontal = residual_norm_squared - float(_vdot(gauge, gauge).real)
        norm_squared += max(horizontal, 0.0)
        work[site] = core
        work[site + 1] = _push_left(work[site + 1], factor)
        phia_left[site + 1] = _phi_next(
            _project(phia_left[site], acores[site], core, "lr"), core, "lr"
        )
        phif_left[site + 1] = _phi_yy_next(
            phif_left[site], core, fcores[site], "lr"
        )
    return math.sqrt(norm_squared) / fnorm


def _true_residual(acores, fcores, xcores, fnorm):
    residual = _ops.sub(_ops.matvec_cores(acores, xcores), fcores)
    return float(_ops.norm(residual) / fnorm)


def lobpcg_solve(
    A,
    f,
    x0,
    eps,
    nswp=100,
    local_steps=20,
    local_prec="c",
    verb=1,
    *,
    forcing_gamma=0.1,
    forcing_power=1.0,
    forcing_min=1e-10,
    forcing_max=1e-2,
    check_true_res=False,
    return_info=False,
):
    """Minimize an SPD TT energy at the fixed rank profile of ``x0``.

    Args:
        A: Square Hermitian positive-definite TT matrix.
        f: TT right-hand side.
        x0: Initial TT vector.  Its complete rank profile is kept unchanged.
        eps: Requested relative horizontal projected-gradient norm.
        nswp: Maximum number of one-site sweeps.
        local_steps: Total local trial budget.  After the first sweep, one
            slot is the transported direction and at most ``local_steps-1``
            slots are fresh PCG directions.
        local_prec: ``'c'`` central block Jacobi (default), ``'l'`` left,
            ``'r'`` right, or ``'n'`` for no local preconditioner.
        verb: Zero is silent; one prints a line per sweep; two also prints
            every local solve.
        forcing_gamma, forcing_power, forcing_min, forcing_max: The local
            forcing tolerance is
            ``clip(gamma * projected_gradient**power, min, max)``.
        check_true_res: Also compute ``||A x-f||/||f||`` for the returned
            tensor.  This may be expensive because the ranks of ``A`` and
            ``x`` multiply; it is not needed for fixed-rank stationarity.
        return_info: Return ``(x, info)`` instead of only ``x``.

    Returns:
        A TT vector with exactly the rank profile of ``x0``.  The history is
        attached as ``x.lobpcg_info`` and optionally returned explicitly.

    Raises:
        ValueError: For incompatible modes, an infeasible rank profile, a
            zero right-hand side, or invalid iteration/tolerance arguments.
        NotImplementedError: For an unknown local preconditioner.

    Example:
        >>> import tt
        >>> A = tt.qlaplace_dd([6, 6])
        >>> exact = tt.rand(2, 12, r=4)
        >>> rhs = tt.matvec(A, exact)
        >>> x0 = tt.rand(2, 12, r=4)
        >>> x, info = tt.lobpcg_solve(
        ...     A, rhs, x0, 1e-8, local_steps=8, verb=0, return_info=True
        ... )
        >>> info.converged
        True
    """
    started = time.time()
    tol = float(eps)
    if not math.isfinite(tol) or tol < 0.0:
        raise ValueError(f"eps={eps!r}: expected a finite non-negative value")
    if int(nswp) < 1:
        raise ValueError(f"nswp={nswp!r}: expected an integer >= 1")
    if int(local_steps) < 1:
        raise ValueError(
            f"local_steps={local_steps!r}: expected an integer >= 1"
        )
    forcing_values = (forcing_gamma, forcing_power, forcing_min, forcing_max)
    if not all(math.isfinite(float(value)) for value in forcing_values):
        raise ValueError("forcing parameters must be finite")
    if forcing_gamma <= 0 or forcing_power <= 0:
        raise ValueError("forcing_gamma and forcing_power must be positive")
    if forcing_min <= 0 or forcing_max < forcing_min:
        raise ValueError("expected 0 < forcing_min <= forcing_max")
    if x0 is None:
        raise ValueError(
            "lobpcg_solve is a fixed-rank method: pass x0 to prescribe its "
            "rank profile"
        )

    prec_kind = _canon_prec(local_prec)
    fcores, f_is_vector = _vector_cores(f)
    xcores, _ = _vector_cores(x0)
    depth = len(fcores)
    acores = _matrix_cores(A, depth)

    row_modes = [int(core.shape[1]) for core in acores]
    column_modes = [int(core.shape[2]) for core in acores]
    if row_modes != column_modes:
        raise ValueError(
            "lobpcg_solve needs a square operator, got row modes "
            f"{row_modes} and column modes {column_modes}"
        )
    if [int(core.shape[1]) for core in fcores] != row_modes:
        raise ValueError("the modes of f do not match the row modes of A")
    if [int(core.shape[1]) for core in xcores] != column_modes:
        raise ValueError("the modes of x0 do not match the column modes of A")

    try:
        dtype = bk.result_dtype(bk.dtype_of(acores[0]), bk.dtype_of(fcores[0]),
                                bk.dtype_of(xcores[0]))
    except TypeError:
        # Integer (or otherwise non-inexact) cores carry no working precision of
        # their own; float64 is what the arithmetic below needs.
        dtype = "float64"
    # ``x0`` owns the device: the answer has its rank profile and must come back
    # where it came from, so ``A`` and ``f`` are brought to that backend.
    try:
        home = bk.backend_of(xcores[0])
    except TypeError:
        home = None                      # non-inexact host cores: default backend
    acores = [bk.asarray(core, dtype, backend=home) for core in acores]
    fcores = [bk.asarray(core, dtype, backend=home) for core in fcores]
    xcores = [bk.copy(bk.asarray(core, dtype, backend=home))
              for core in xcores]
    target_ranks = _check_fixed_profile(xcores)
    fnorm = float(_ops.norm(fcores))
    if fnorm == 0.0:
        raise ValueError(
            "lobpcg_solve: f is zero, so a relative stopping quantity is "
            "undefined; the solution is tt.zeros"
        )

    one = _ones((1, 1, 1), xcores[0])
    one2 = _ones((1, 1), xcores[0])
    projected = _projected_gradient_norm(
        acores, fcores, xcores, fnorm, one, one2
    )
    info = LOBPCGSolveHistory(
        tol=tol,
        projected_gradient=projected,
        initial_projected_gradient=projected,
        ranks=list(target_ranks),
    )
    best_cores = _copy_cores(xcores)
    best_projected = projected

    memories = [None] * depth
    old_left_frame = None
    old_right_frame = None
    if projected <= tol:
        info.converged = True

    for sweep in range(1, int(nswp) + 1):
        if info.converged:
            break
        forcing = min(
            float(forcing_max),
            max(
                float(forcing_min),
                float(forcing_gamma) * projected ** float(forcing_power),
            ),
        )
        real_tol = forcing / math.sqrt(max(depth - 1, 1)) / RESID_DAMP
        phia_right, phif_right, current_right_frame = _right_canonicalize(
            acores, fcores, xcores, one, one2
        )
        right_overlaps = (
            _right_frame_overlaps(old_right_frame, current_right_frame)
            if old_right_frame is not None
            else None
        )
        left_overlap = _ones((1, 1), xcores[0])
        phia_left = _interfaces(depth, one)
        phif_left = _interfaces(depth, one2)
        max_dx = 0.0
        max_incoming = 0.0
        sweep_matvecs = 0
        sweep_recycled = 0
        sweep_fresh = 0
        sweep_breakdowns = 0

        for site in range(depth):
            transported = None
            if memories[site] is not None and right_overlaps is not None:
                transported = _valid_direction(
                    _transport_direction(
                        memories[site], left_overlap, right_overlaps[site + 1]
                    )
                )
            rhs = _local_rhs(
                phif_left[site], fcores[site], phif_right[site + 1]
            )
            apply, _ = _local_operator(
                phia_left[site], acores[site], phia_right[site + 1]
            )
            residual = apply(xcores[site]) - rhs
            rhs_norm = float(bk.norm(rhs))
            scale = rhs_norm if rhs_norm > 0.0 else 1.0
            incoming = float(bk.norm(residual)) / scale
            max_incoming = max(max_incoming, incoming)
            local_info = None
            if incoming > real_tol:
                local_tol = min(0.1,
                                real_tol / max(incoming * incoming, _TINY))
                correction, next_memory, local_info = _augmented_pcg(
                    phia_left[site],
                    acores[site],
                    phia_right[site + 1],
                    residual,
                    transported,
                    local_tol,
                    int(local_steps),
                    prec_kind,
                )
                xcores[site] = xcores[site] - correction
                correction_norm = float(bk.norm(correction))
                core_norm = float(bk.norm(xcores[site]))
                max_dx = max(
                    max_dx,
                    correction_norm / core_norm if core_norm > 0 else correction_norm,
                )
                memories[site] = next_memory
                sweep_matvecs += local_info["matvecs"]
                sweep_recycled += local_info["coarse_used"]
                sweep_fresh += local_info["fresh_steps"]
                sweep_breakdowns += int(local_info["breakdown"])
                if verb > 1:
                    print(
                        f"lobpcg_solve: swp={sweep}, core={site}, "
                        f"in={incoming:.3E}, out="
                        f"{local_info['relative_residual']:.3E}, "
                        f"fresh={local_info['fresh_steps']}, "
                        f"recycled={local_info['coarse_used']}"
                    )
            else:
                # Even a skipped local solve must advance the stored vector to
                # the current chart; otherwise its frame metadata and entries
                # would refer to different sweeps.
                memories[site] = transported

            if site == depth - 1:
                continue
            core, factor = _qr_left(xcores[site])
            if old_left_frame is not None:
                old_core = old_left_frame[site]
                contracted = (
                    left_overlap
                    @ old_core.reshape(
                        old_core.shape[0], old_core.shape[1] * old_core.shape[2]
                    )
                ).reshape(core.shape[0] * core.shape[1], old_core.shape[2])
                left_overlap = _conj_t(core.reshape(
                    core.shape[0] * core.shape[1], core.shape[2]
                )) @ contracted
            xcores[site] = core
            xcores[site + 1] = _push_left(xcores[site + 1], factor)
            phia_left[site + 1] = _phi_next(
                _project(phia_left[site], acores[site], core, "lr"),
                core,
                "lr",
            )
            phif_left[site + 1] = _phi_yy_next(
                phif_left[site], core, fcores[site], "lr"
            )

        actual_ranks = [int(value) for value in _ops.ranks(xcores)]
        if actual_ranks != target_ranks:
            raise RuntimeError(
                "lobpcg_solve changed the fixed rank profile: expected "
                f"{target_ranks}, got {actual_ranks}"
            )
        old_left_frame = _copy_cores(xcores)
        old_right_frame = current_right_frame
        projected = _projected_gradient_norm(
            acores, fcores, xcores, fnorm, one, one2
        )
        entry = {
            "sweep": sweep,
            "projected_gradient": projected,
            "max_dx": max_dx,
            "max_incoming_local_residual": max_incoming,
            "forcing_tolerance": forcing,
            "local_matvecs": sweep_matvecs,
            "fresh_directions": sweep_fresh,
            "recycled_directions": sweep_recycled,
            "breakdowns": sweep_breakdowns,
            "max_rank": max(actual_ranks),
            "time": time.time() - started,
        }
        info.sweeps.append(entry)
        info.projected_gradient = projected
        info.nswp_done = sweep
        info.local_matvecs += sweep_matvecs
        info.recycled_directions += sweep_recycled
        if projected < best_projected:
            best_projected = projected
            best_cores = _copy_cores(xcores)
        if verb > 0:
            print(
                f"lobpcg_solve: swp={sweep}, "
                f"projected_gradient={projected:9.3E}, "
                f"max_dx={max_dx:9.3E}, matvecs={sweep_matvecs}, "
                f"recycled={sweep_recycled}, max_rank={max(actual_ranks)}"
            )
        if projected <= tol:
            info.converged = True
            break

    if best_projected < projected:
        xcores = best_cores
        projected = best_projected
        info.projected_gradient = projected
    info.ranks = [int(value) for value in _ops.ranks(xcores)]
    if check_true_res:
        info.true_res = _true_residual(acores, fcores, xcores, fnorm)
    info.time = time.time() - started
    if info.converged:
        info.message = (
            f"converged in {info.nswp_done} sweeps: projected gradient "
            f"{info.projected_gradient:.3E}"
        )
    else:
        info.message = (
            f"lobpcg_solve did NOT reach eps={tol:.3E} in "
            f"{info.nswp_done} sweeps: projected gradient "
            f"{info.projected_gradient:.3E} at fixed ranks {info.ranks}"
        )
        warnings.warn(info.message, UserWarning, stacklevel=2)

    if f_is_vector:
        result = vector.from_list(xcores)
        result.lobpcg_info = info
    else:
        result = xcores
    return (result, info) if return_info else result
